In [1]:
import pandas as pd
import numpy as np

## 1 Creating a dataframe from an array

### 1.1 Option 1

In [3]:
# creating an array 
data = np.array([[1,4],[2,5],[3,6]])

In [4]:
# creating a dataframe 
pd.DataFrame(data)

   0  1
0  1  4
1  2  5
2  3  6

In [7]:
# creating a dataframe 2, the data frame can be shown wihout df and by running ctrl+enter
df=pd.DataFrame(data, index=["row1", "row2","row3"], columns=["col1", "col2"])

In [8]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### 1.2 Option 2

In [ ]:
# creating an array with list shape
data = [[1,4],[2,5],[3,6]]

In [9]:
# creating a dataframe
df=pd.DataFrame(data, index=["row1", "row2","row3"], columns=["col1", "col2"])

In [10]:
# showing a dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## 2 Creating a DataFrame from a dictionary

In [11]:
# lists used for this example
states = ["California", "Texas", "Florida", "New York"]
population = [39613493, 29730311, 21944577, 19299981]

In [12]:
# storing lists within a dictionary
dict_states = {'States': states, 'Population': population}

In [13]:
# creating the dataframe 
df_population = pd.DataFrame(dict_states)
# df_population = pd.DataFrame.from_dict(dict_states)

In [14]:
# showing the dataframe
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

## 3 Creating a DataFrame from a csv file

In [18]:
# reading the csv file

df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')

In [17]:
# to check your current working directory
import os
print(os.getcwd())

C:\Users\Brigita

In [19]:
# show first 5 rows in a dataframe
df_exams.head()
# to see the summeury
# df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Unnamed: 8
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75