In [1]:
import pandas as pd

In [2]:
# reading the csv file or it has to be located in the same folder where your jupyter notebook is located.
# should it be in the same directory the csv file could be read like this: df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')

In [3]:
# show first 5 rows in a dataframe
df_exams.head()
# seing summury
# df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,72,72
1,1,female,group C,some college,standard,completed,69,90
2,2,female,group B,master's degree,standard,none,90,95
3,3,male,group A,associate's degree,free/reduced,none,47,57
4,4,male,group C,some college,standard,none,76,78

In [4]:
# show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,995,female,group E,master's degree,standard,completed,88,99
996,996,male,group C,high school,free/reduced,none,62,55
997,997,female,group C,high school,free/reduced,completed,59,71
998,998,female,group D,some college,standard,completed,68,78
999,999,female,group D,some college,free/reduced,none,77,86

In [5]:
# show last n rows in a dataframe
df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,990,male,group E,high school,free/reduced,completed,86,81
991,991,female,group B,some high school,standard,completed,65,82
992,992,female,group D,associate's degree,free/reduced,none,55,76
993,993,female,group D,bachelor's degree,free/reduced,none,62,72
994,994,male,group A,high school,standard,none,63,63
995,995,female,group E,master's degree,standard,completed,88,99
996,996,male,group C,high school,free/reduced,none,62,55
997,997,female,group C,high school,free/reduced,completed,59,71
998,998,female,group D,some college,standard,completed,68,78
999,999,female,group D,some college,free/reduced,none,77,86

In [6]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [9]:
# display n rows
pd.set_option('display.max_rows', 1000)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,72,72
1,1,female,group C,some college,standard,completed,69,90
2,2,female,group B,master's degree,standard,none,90,95
3,3,male,group A,associate's degree,free/reduced,none,47,57
4,4,male,group C,some college,standard,none,76,78
5,5,female,group B,associate's degree,standard,none,71,83
6,6,female,group B,some college,standard,completed,88,95
7,7,male,group B,some college,free/reduced,none,40,43
8,8,male,group D,high school,free/reduced,completed,64,64
9,9,female,group B,high school,free/reduced,none,38,60
10,10,male,group C,associate's degree,standard,none,58,54
11,11,male,group D,associate's degree,standard,none,40,52
12,12,female,group B,high school,standard,none,65,81
13,13,male,group A,some college,standard,completed,78,72
14,14,female,group A,master's degree,standard,none,50,53
15,15,female,group C,some high school,standard,none,69,75
16,16,male,group C,high school,standard,none,88,89
17,17,female,group B,some high school,free/reduced,none,18,32
18,18,male,group C,master's degree,free/reduced,completed,46,42
19,19,female,group C,associate's degree,free/reduced,none,54,58
20,20,male,group D,high school,standard,none,66,69
21,21,female,group B,some college,free/reduced,completed,65,75
22,22,male,group D,some college,standard,none,44,54
23,23,female,group C,some high school,standard,none,69,73
24,24,male,group D,bachelor's degree,free/reduced,completed,74,71
25,25,male,group A,master's degree,free/reduced,none,73,74
26,26,male,group B,some college,standard,none,69,54
27,27,female,group C,bachelor's degree,standard,none,67,69
28,28,male,group C,high school,standard,none,70,70
29,29,female,group D,master's degree,standard,none,62,70
30,30,female,group D,some college,standard,none,69,74
31,31,female,group B,some college,standard,none,63,65
32,32,female,group E,master's degree,free/reduced,none,56,72
33,33,male,group D,some college,standard,none,40,42
34,34,male,group E,some college,standard,none,97,87
35,35,male,group E,associate's degree,standard,completed,81,81
36,36,female,group D,associate's degree,standard,none,74,81
37,37,female,group D,some high school,free/reduced,none,50,64
38,38,female,group D,associate's degree,free/reduced,completed,75,90
39,39,male,group B,associate's degree,free/reduced,none,57,56
40,40,male,group C,associate's degree,free/reduced,none,55,61
41,41,female,group C,associate's degree,standard,none,58,73
42,42,female,group B,associate's degree,standard,none,53,58
43,43,male,group B,some college,free/reduced,completed,59,65
44,44,female,group E,associate's degree,free/reduced,none,50,56
45,45,male,group B,associate's degree,standard,none,65,54
46,46,female,group A,associate's degree,standard,completed,55,65
47,47,female,group C,high school,standard,none,66,71
48,48,female,group D,associate's degree,free/reduced,completed,57,74
49,49,male,group C,high school,standard,completed,82,84
50,50,male,group E,some college,standard,none,53,55
51,51,male,group E,associate's degree,free/reduced,completed,77,69
52,52,male,group C,some college,standard,none,53,44
53,53,male,group D,high school,standard,none,88,78
54,54,female,group C,some high school,free/reduced,completed,71,84
55,55,female,group C,high school,free/reduced,none,33,41
56,56,female,group E,associate's degree,standard,completed,82,85
57,57,male,group D,associate's degree,standard,none,52,55
58,58,male,group D,some college,standard,completed,58,59
59,59,female,group C,some high school,free/reduced,none,0,17
60,60,male,group E,bachelor's degree,free/reduced,completed,79,74
61,61,male,group A,some high school,free/reduced,none,39,39
62,62,male,group A,associate's degree,free/reduced,none,62,61
63,63,female,group C,associate's degree,standard,none,69,80
64,64,female,group D,some high school,standard,none,59,58
65,65,male,group B,some high school,standard,none,67,64
66,66,male,group D,some high school,free/reduced,none,45,37
67,67,female,group C,some college,standard,none,60,72
68,68,male,group B,associate's degree,free/reduced,none,61,58
69,69,female,group C,associate's degree,standard,none,39,64
70,70,female,group D,some college,free/reduced,completed,58,63
71,71,male,group D,some college,standard,completed,63,55
72,72,female,group A,associate's degree,free/reduced,none,41,51
73,73,male,group C,some high school,free/reduced,none,61,57
74,74,male,group C,some high school,standard,none,49,49
75,75,male,group B,associate's degree,free/reduced,none,44,41
76,76,male,group E,some high school,standard,none,30,26
77,77,male,group A,bachelor's degree,standard,completed,80,78
78,78,female,group D,some high school,standard,completed,61,74
79,79,female,group E,master's degree,standard,none,62,68
80,80,female,group B,associate's degree,standard,none,47,49
81,81,male,group B,high school,free/reduced,none,49,45
82,82,male,group A,some college,free/reduced,completed,50,47
83,83,male,group E,associate's degree,standard,none,72,64
84,84,male,group D,high school,free/reduced,none,42,39
85,85,female,group C,some college,standard,none,73,80
86,86,female,group C,some college,free/reduced,none,76,83
87,87,female,group D,associate's degree,standard,none,71,71
88,88,female,group A,some college,standard,none,58,70
89,89,female,group D,some high school,standard,none,73,86
90,90,female,group C,bachelor's degree,standard,none,65,72
91,91,male,group C,high school,free/reduced,none,27,34
92,92,male,group C,high school,standard,none,71,79
93,93,male,group C,associate's degree,free/reduced,completed,43,45
94,94,female,group B,some college,standard,none,79,86
95,95,male,group C,associate's degree,free/reduced,completed,78,81
96,96,male,group B,some high school,standard,completed,65,66
97,97,female,group E,some college,standard,completed,63,72
98,98,female,group D,some college,free/reduced,none,58,67
99,99,female,group D,bachelor's degree,standard,none,65,67
100,100,male,group B,some college,standard,none,79,67
101,101,male,group D,bachelor's degree,standard,completed,68,74
102,102,female,group D,associate's degree,standard,none,85,91
103,103,male,group B,high school,standard,completed,60,44
104,104,male,group C,some college,standard,completed,98,86
105,105,female,group C,some college,standard,none,58,67
106,106,female,group D,master's degree,standard,none,87,100
107,107,male,group E,associate's degree,standard,completed,66,63
108,108,female,group B,associate's degree,free/reduced,none,52,76
109,109,female,group B,some high school,standard,none,70,64
110,110,female,group D,associate's degree,free/reduced,completed,77,89
111,111,male,group C,high school,standard,none,62,55
112,112,male,group A,associate's degree,standard,none,54,53
113,113,female,group D,some college,standard,none,51,58
114,114,female,group E,bachelor's degree,standard,completed,99,100
115,115,male,group C,high school,standard,none,84,77
116,116,female,group B,bachelor's degree,free/reduced,none,75,85
117,117,female,group D,bachelor's degree,standard,none,78,82
118,118,female,group D,some high school,standard,none,51,63
119,119,female,group C,some college,standard,none,55,69
120,120,female,group C,bachelor's degree,standard,completed,79,92
121,121,male,group B,associate's degree,standard,completed,91,89
122,122,female,group C,some college,standard,completed,88,93
123,123,male,group D,high school,free/reduced,none,63,57
124,124,male,group E,some college,standard,none,83,80
125,125,female,group B,high school,standard,none,87,95
126,126,male,group B,some high school,standard,none,72,68
127,127,male,group D,some college,standard,completed,65,77
128,128,male,group D,master's degree,standard,none,82,82
129,129,female,group A,bachelor's degree,standard,none,51,49
130,130,male,group D,master's degree,standard,none,89,84
131,131,male,group C,some high school,free/reduced,completed,53,37
132,132,male,group E,some college,free/reduced,completed,87,74
133,133,female,group C,some college,standard,completed,75,81
134,134,male,group D,bachelor's degree,free/reduced,completed,74,79
135,135,male,group C,bachelor's degree,standard,none,58,55
136,136,male,group B,some high school,standard,completed,51,54
137,137,male,group E,high school,standard,none,70,55
138,138,female,group C,associate's degree,standard,none,59,66
139,139,male,group D,some college,standard,completed,71,61
140,140,female,group D,some high school,standard,none,76,72
141,141,female,group C,some college,free/reduced,none,59,62
142,142,female,group E,some college,free/reduced,completed,42,55
143,143,male,group A,high school,standard,none,57,43
144,144,male,group D,some college,standard,none,88,73
145,145,female,group C,some college,free/reduced,none,22,39
146,146,male,group B,some high school,standard,none,88,84
147,147,male,group C,associate's degree,free/reduced,none,73,68
148,148,female,group D,bachelor's degree,standard,completed,68,75
149,149,male,group E,associate's degree,free/reduced,completed,100,100
150,150,male,group A,some high school,standard,completed,62,67
151,151,male,group A,bachelor's degree,standard,none,77,67
152,152,female,group B,associate's degree,standard,completed,59,70
153,153,male,group D,bachelor's degree,standard,none,54,49
154,154,male,group D,some high school,standard,none,62,67
155,155,female,group C,some college,standard,completed,70,89
156,156,female,group E,high school,free/reduced,completed,66,74
157,157,male,group B,some college,free/reduced,none,60,60
158,158,female,group B,associate's degree,standard,completed,61,86
159,159,male,group D,associate's degree,free/reduced,none,66,62
160,160,male,group B,associate's degree,free/reduced,completed,82,78
161,161,female,group E,some college,free/reduced,completed,75,88
162,162,male,group B,master's degree,free/reduced,none,49,53
163,163,male,group C,high school,standard,none,52,53
164,164,female,group E,master's degree,standard,none,81,92
165,165,female,group C,bachelor's degree,standard,completed,96,100
166,166,male,group C,high school,free/reduced,completed,53,51
167,167,female,group B,master's degree,free/reduced,completed,58,76
168,168,female,group B,high school,standard,completed,68,83
169,169,female,group C,some college,free/reduced,completed,67,75
170,170,male,group A,high school,standard,completed,72,73
171,171,male,group E,some high school,standard,none,94,88
172,172,female,group D,some college,standard,none,79,86
173,173,female,group C,associate's degree,standard,none,63,67
174,174,female,group C,bachelor's degree,free/reduced,completed,43,51
175,175,female,group C,master's degree,standard,completed,81,91
176,176,female,group B,high school,free/reduced,completed,46,54
177,177,female,group C,associate's degree,standard,completed,71,77
178,178,female,group B,master's degree,free/reduced,completed,52,70
179,179,female,group D,some high school,standard,completed,97,100
180,180,male,group C,master's degree,free/reduced,completed,62,68
181,181,female,group C,some college,free/reduced,none,46,64
182,182,female,group E,high school,standard,none,50,50
183,183,female,group D,associate's degree,standard,none,65,69
184,184,male,group C,some high school,free/reduced,completed,45,52
185,185,male,group C,associate's degree,free/reduced,completed,65,67
186,186,male,group E,high school,standard,none,80,76
187,187,male,group D,some high school,standard,completed,62,66
188,188,male,group B,some high school,free/reduced,none,48,52
189,189,female,group C,bachelor's degree,standard,none,77,88
190,190,female,group E,associate's degree,standard,none,66,65
191,191,male,group D,some college,standard,completed,76,83
192,192,female,group B,some high school,standard,none,62,64
193,193,male,group D,some college,standard,completed,77,62
194,194,female,group C,master's degree,standard,completed,69,84
195,195,male,group D,associate's degree,standard,none,61,55
196,196,male,group C,some high school,free/reduced,completed,59,69
197,197,male,group E,high school,free/reduced,none,55,56
198,198,female,group B,some college,free/reduced,none,45,53
199,199,female,group B,bachelor's degree,free/reduced,none,78,79
200,200,female,group C,associate's degree,standard,completed,67,84
201,201,female,group D,some college,free/reduced,none,65,81
202,202,male,group C,associate's degree,standard,none,69,77
203,203,female,group B,associate's degree,standard,none,57,69
204,204,male,group C,some college,standard,none,59,41
205,205,male,group D,some high school,standard,completed,74,71
206,206,male,group E,bachelor's degree,standard,none,82,62
207,207,male,group E,high school,standard,completed,81,80
208,208,female,group B,some college,free/reduced,none,74,81
209,209,female,group B,some college,free/reduced,none,58,61
210,210,male,group D,some high school,free/reduced,completed,80,79
211,211,male,group C,some college,free/reduced,none,35,28
212,212,female,group C,high school,free/reduced,none,42,62
213,213,male,group C,associate's degree,free/reduced,completed,60,51
214,214,male,group E,high school,standard,completed,87,91
215,215,male,group B,some high school,standard,completed,84,83
216,216,female,group E,associate's degree,free/reduced,completed,83,86
217,217,female,group C,high school,free/reduced,none,34,42
218,218,male,group B,high school,free/reduced,none,66,77
219,219,male,group B,some high school,standard,completed,61,56
220,220,female,group D,high school,standard,completed,56,68
221,221,male,group B,associate's degree,standard,none,87,85
222,222,female,group C,some high school,free/reduced,none,55,65
223,223,male,group D,some high school,standard,none,86,80
224,224,female,group B,associate's degree,standard,completed,52,66
225,225,female,group E,master's degree,free/reduced,none,45,56
226,226,female,group C,some college,standard,none,72,72
227,227,male,group D,high school,standard,none,57,50
228,228,male,group A,some high school,free/reduced,none,68,72
229,229,female,group C,some college,standard,completed,88,95
230,230,male,group D,some college,standard,none,76,64
231,231,male,group C,associate's degree,standard,none,46,43
232,232,female,group B,bachelor's degree,standard,none,67,86
233,233,male,group E,some high school,standard,none,92,87
234,234,male,group C,bachelor's degree,standard,completed,83,82
235,235,male,group D,associate's degree,standard,none,80,75
236,236,male,group D,bachelor's degree,free/reduced,none,63,66
237,237,female,group D,some high school,standard,completed,64,60
238,238,male,group B,some college,standard,none,54,52
239,239,male,group C,associate's degree,standard,none,84,80
240,240,male,group D,high school,free/reduced,completed,73,68
241,241,female,group E,bachelor's degree,standard,none,80,83
242,242,female,group D,high school,standard,none,56,52
243,243,male,group E,some college,standard,none,59,51
244,244,male,group D,some high school,standard,none,75,74
245,245,male,group C,associate's degree,standard,none,85,76
246,246,male,group E,associate's degree,standard,none,89,76
247,247,female,group B,high school,standard,completed,58,70
248,248,female,group B,high school,standard,none,65,64
249,249,male,group C,high school,standard,none,68,60
250,250,male,group A,some high school,standard,completed,47,49
251,251,female,group D,some college,free/reduced,none,71,83
252,252,female,group B,some high school,standard,completed,60,70
253,253,male,group D,master's degree,standard,none,80,80
254,254,male,group D,high school,standard,none,54,52
255,255,female,group E,some college,standard,none,62,73
256,256,female,group C,associate's degree,free/reduced,none,64,73
257,257,male,group C,associate's degree,standard,completed,78,77
258,258,female,group B,some college,standard,none,70,75
259,259,female,group C,master's degree,free/reduced,completed,65,81
260,260,female,group C,some high school,free/reduced,completed,64,79
261,261,male,group C,some college,standard,completed,79,79
262,262,female,group C,some high school,free/reduced,none,44,50
263,263,female,group E,high school,standard,none,99,93
264,264,male,group D,high school,standard,none,76,73
265,265,male,group D,some high school,free/reduced,none,59,42
266,266,female,group C,bachelor's degree,standard,none,63,75
267,267,female,group D,high school,standard,none,69,72
268,268,female,group D,associate's degree,standard,completed,88,92
269,269,female,group E,some college,free/reduced,none,71,76
270,270,male,group C,bachelor's degree,standard,none,69,63
271,271,male,group C,some college,standard,none,58,49
272,272,female,group D,associate's degree,free/reduced,none,47,53
273,273,female,group D,some college,standard,none,65,70
274,274,male,group B,some college,standard,completed,88,85
275,275,male,group C,bachelor's degree,standard,none,83,78
276,276,female,group C,some high school,standard,completed,85,92
277,277,female,group E,high school,standard,completed,59,63
278,278,female,group C,some high school,free/reduced,none,65,86
279,279,male,group B,bachelor's degree,free/reduced,none,73,56
280,280,male,group D,high school,standard,none,53,52
281,281,male,group D,high school,standard,none,45,48
282,282,female,group D,bachelor's degree,free/reduced,none,73,79
283,283,female,group D,some college,free/reduced,completed,70,78
284,284,female,group B,some high school,standard,none,37,46
285,285,male,group B,associate's degree,standard,completed,81,82
286,286,male,group E,associate's degree,standard,completed,97,82
287,287,female,group B,some high school,standard,none,67,89
288,288,male,group B,bachelor's degree,free/reduced,none,88,75
289,289,male,group E,some high school,standard,completed,77,76
290,290,male,group C,associate's degree,standard,none,76,70
291,291,male,group D,some high school,standard,none,86,73
292,292,male,group C,some high school,standard,completed,63,60
293,293,female,group E,bachelor's degree,standard,none,65,73
294,294,male,group D,high school,free/reduced,completed,78,77
295,295,male,group B,associate's degree,free/reduced,none,67,62
296,296,male,group A,some high school,standard,completed,46,41
297,297,male,group E,associate's degree,standard,completed,71,74
298,298,male,group C,high school,free/reduced,completed,40,46
299,299,male,group D,associate's degree,free/reduced,none,90,87
300,300,male,group A,some college,free/reduced,completed,81,78
301,301,male,group D,some high school,free/reduced,none,56,54
302,302,female,group C,associate's degree,standard,completed,67,84
303,303,male,group B,associate's degree,standard,none,80,76
304,304,female,group C,associate's degree,standard,completed,74,75
305,305,male,group A,some college,standard,none,69,67
306,306,male,group E,some college,standard,completed,99,87
307,307,male,group C,some high school,standard,none,51,52
308,308,female,group B,associate's degree,free/reduced,none,53,71
309,309,female,group D,high school,free/reduced,none,49,57
310,310,female,group B,associate's degree,standard,none,73,76
311,311,male,group B,bachelor's degree,standard,none,66,60
312,312,male,group D,bachelor's degree,standard,completed,67,61
313,313,female,group C,associate's degree,free/reduced,completed,68,67
314,314,female,group C,bachelor's degree,standard,completed,59,64
315,315,male,group C,high school,standard,none,71,66
316,316,female,group D,master's degree,standard,completed,77,82
317,317,male,group C,associate's degree,standard,none,83,72
318,318,male,group B,bachelor's degree,standard,none,63,71
319,319,female,group D,associate's degree,free/reduced,none,56,65
320,320,female,group C,high school,free/reduced,completed,67,79
321,321,female,group E,high school,standard,none,75,86
322,322,female,group C,some college,standard,none,71,81
323,323,female,group C,some high school,free/reduced,none,43,53
324,324,female,group C,high school,free/reduced,none,41,46
325,325,female,group C,some college,standard,none,82,90
326,326,male,group C,some college,standard,none,61,61
327,327,male,group A,some college,free/reduced,none,28,23
328,328,male,group C,associate's degree,standard,completed,82,75