In [1]:
import pandas as pd

In [30]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')

In [31]:
# showing the dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Attributes

In [6]:
# getting access to the shape attribute, how many rows and columns the dataframe has
df_exams.shape

(1000, 8)

In [7]:
# getting access to the index attribute. the dataframe starts at 0, stops at 1000 and increases by one step( 0,1,2,3)
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [8]:
# getting access to the column attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [32]:
# data types of each column str are objects
df_exams.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

## Methods

In [33]:
# showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

In [34]:
# describing basic statistics of the dataframe. std=standard
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      69.169000
std      15.16308      14.600192      14.600192
min       0.00000      17.000000      17.000000
25%      57.00000      59.000000      59.000000
50%      66.00000      70.000000      70.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [35]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

## Functions

In [14]:
# obtaining the length of the dataframe (number of rows)
len(df_exams)

1000

In [15]:
# obtaining the highest index of the dataframe
max(df_exams.index)

999

In [16]:
# obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [17]:
# obtaining the data type
type(df_exams)

pandas.DataFrame

In [36]:
# rounding the values of the dataset
round(df_exams, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,99
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,71
998,female,group D,some college,standard,completed,68,78,78
999,female,group D,some college,free/reduced,none,77,86,86