In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Adding a new column

### Adding a new column with a scalar value

In [3]:
# adding new column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,72,70
1,female,group C,some college,standard,completed,69,90,90,70
2,female,group B,master's degree,standard,none,90,95,95,70
3,male,group A,associate's degree,free/reduced,none,47,57,57,70
4,male,group C,some college,standard,none,76,78,78,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,99,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,71,70
998,female,group D,some college,standard,completed,68,78,78,70
999,female,group D,some college,free/reduced,none,77,86,86,70

### Adding a new column with an array

The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [4]:
# import numpy
import numpy as np

In [5]:
# create an array of 1000 elements
language_score = np.arange(0, 1000)

In [6]:
# length of the array
len(language_score)

1000

In [7]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,72,0
1,female,group C,some college,standard,completed,69,90,90,1
2,female,group B,master's degree,standard,none,90,95,95,2
3,male,group A,associate's degree,free/reduced,none,47,57,57,3
4,male,group C,some college,standard,none,76,78,78,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,99,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,71,997
998,female,group D,some college,standard,completed,68,78,78,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [8]:
# create random !!! integer !!! numbers between 1 and 100. does not include 100 as it ends on 99, but could include if we state 101.
int_language_score = np.random.randint(1, 100, size=1000)

In [9]:
# min value inclusive and high value exclusive
print(min(int_language_score))
print(max(int_language_score))

1
99

In [10]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,72,96
1,female,group C,some college,standard,completed,69,90,90,54
2,female,group B,master's degree,standard,none,90,95,95,68
3,male,group A,associate's degree,free/reduced,none,47,57,57,16
4,male,group C,some college,standard,none,76,78,78,32
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,99,81
996,male,group C,high school,free/reduced,none,62,55,55,69
997,female,group C,high school,free/reduced,completed,59,71,71,5
998,female,group D,some college,standard,completed,68,78,78,69
999,female,group D,some college,free/reduced,none,77,86,86,66

In [11]:
# create random !!! float !!! numbers between 1 and 100 , and incluges nearly 100 (99.9)
np.random.uniform(1, 100, size=1000)

array([86.61820258, 59.31940233, 91.59442205, 66.47722968, 43.6896378 ,
       77.47208743, 86.11011884, 12.60507177, 14.66017653, 82.91732659,
       26.34385201, 75.78039171,  7.25106511,  2.30437776, 46.1573168 ,
        2.73483747, 83.80673092, 40.05751337, 67.44916807, 39.20408589,
       20.05745729, 72.08323452, 47.01353582, 34.96596669, 79.40980677,
       27.20879589, 66.04984853, 77.36367154, 18.77595493,  5.32896523,
       12.69159571, 83.30299388, 24.29271621, 42.52857059, 18.76680469,
        1.496648  , 80.23688548, 27.95070802, 63.170998  , 87.7400771 ,
        5.31893917, 22.44103808, 15.56651395, 11.85348975, 31.61039706,
        5.08429562, 64.78528804, 56.2909097 , 90.948098  , 42.13524246,
       75.92908497, 34.41263883, 58.3708273 , 48.55791349, 56.39727977,
       50.14361661, 32.22209227, 62.67526113, 20.17780003, 10.04868266,
       75.60964431,  3.79684402, 47.17758868, 44.48672496, 51.51764119,
       67.57728699, 49.36917288, 94.39152586, 91.26379553, 67.79851529,
       10.37304703, 22.74044296, 20.44360614,  3.68123917, 10.4258767 ,
       63.55467829, 47.7162159 , 83.7770231 , 32.06805995, 83.19953975,
       36.39997114, 95.67604842, 46.54085659, 21.80996767, 49.91503163,
       18.84917801, 54.15188456, 83.85468505, 86.56302722, 28.30960595,
       62.13073587, 55.57515019, 24.83927906, 62.16921171, 44.1062568 ,
       84.63507173, 49.46524626, 12.54342001, 43.88186452, 35.01843327,
       49.93264024, 21.44540296, 94.99092253, 88.78426048, 30.54416687,
       64.63214471, 83.80378131, 53.23336018, 62.00300093, 13.07209241,
       14.46841194, 88.84309688, 76.77054574, 66.81515497, 44.86791845,
       57.87789093, 15.38857095, 90.77132507, 77.2485612 , 83.23366048,
       79.38519543,  5.35868807, 99.05143418, 83.91939528, 91.3045976 ,
       10.35288461, 81.91307922, 96.19551744, 88.45676683, 39.93234095,
       60.52386259, 52.79513218, 36.30762879, 97.85522416, 84.33037707,
        3.010414  , 62.62068237, 65.8084603 , 89.92796486, 15.49874248,
       73.77118049,  2.25144202, 61.19230962, 93.8740127 , 15.94542891,
       66.50478403, 39.95382448, 72.80189693, 50.5732951 , 20.92106428,
       65.71745522, 81.70426503, 77.53830063, 81.17006639, 43.19123478,
       73.85104122, 80.63740971, 48.30506278, 48.76319657, 26.82087571,
       82.36266414, 44.66043382, 96.50346795, 91.13164571, 24.67369586,
       48.99074743, 83.29925145, 88.46267972, 44.60796943, 31.41729438,
       15.4439163 , 52.52696164, 59.12590476, 10.01697077,  2.41391751,
       38.07369466,  3.24131296, 71.60907999, 69.71419052, 95.75942129,
       80.09791823, 40.233621  , 40.54557302, 26.91475327, 51.42709399,
        3.66770902, 53.73125328, 83.58811446, 92.56030581, 19.0047021 ,
       40.75960322, 21.22694743, 43.48401958, 41.0102658 , 15.17670684,
       57.10268012, 62.41997461, 35.54677791, 20.64762724, 93.86762403,
        8.84959452, 88.59404117, 29.76783567,  1.23875862, 23.58518109,
       98.10359469, 66.55167312, 27.71788213, 70.05185607, 33.99139328,
        1.37546086,  7.95941444, 66.54598072, 75.80313812, 52.8327786 ,
       80.56987905, 56.84543869, 31.88686724, 86.79625065, 34.84897807,
       28.9168642 , 63.95522283, 96.60081237, 75.4442057 , 84.39257214,
       47.52595937, 23.96487567,  9.63248512, 63.7732433 ,  1.04454263,
       71.27711033, 96.79327497, 96.0554122 , 24.46544197,  4.58695629,
       80.63219383, 22.89327604, 37.22637778, 35.54802705, 90.07606396,
       97.37880838, 48.15029032, 59.41114298, 99.51559281, 94.44867497,
       50.81381585, 69.60365183, 80.31723781, 91.63295329, 61.64237532,
       84.88393415, 89.99550625, 40.40969574, 42.88762937, 84.25757705,
       58.18010039, 22.99985102, 29.55427573, 24.07108985, 39.56614991,
       39.19107102, 46.17202641, 43.85197153, 31.9977081 , 39.92458158,
        6.73011925, 61.28518627, 60.50061077, 27.36510916, 19.99767603,
       45.6668864 , 90.89483838, 88.21703656, 24.65642066, 83.57866141,
       91.38980855, 15.17606463, 57.409368  , 86.68929118, 51.23587227,
        4.2313243 , 93.74500281, 75.54884809, 87.634572  , 87.49598761,
       96.36100561, 30.70011242, 42.64181852, 19.03256589, 20.77271813,
       21.26140132, 79.52661304, 16.77821769,  8.76182831, 27.191279  ,
       66.97090072,  2.18919948, 18.60474601, 35.55293312, 54.13112237,
        2.91062361, 11.20680451, 22.038272  , 69.60457189, 58.42551146,
       50.35499413, 42.72965558, 15.74362177, 82.24694185, 76.27867604,
       99.76766573, 25.61962692, 67.92701672, 84.95971914, 92.72807415,
       84.89630828, 14.37253916, 52.15665254, 18.9418634 , 76.60647453,
       43.31735252, 83.36678822, 67.34923762, 83.34528434, 44.47878486,
       79.78659007, 11.98728298, 62.78942041, 70.16455581, 99.13979865,
       41.10411806, 15.31718949, 33.12797592, 23.71519096,  3.66314703,
        7.5233434 , 87.17834117, 66.86336366, 22.43509685, 13.22635758,
       40.65535598, 77.19414811,  7.71262922, 68.30056073, 29.92807583,
       63.79474235, 79.27909648, 99.96090508,  5.65730264, 66.37390703,
       69.79291285, 46.44951361, 54.54768317, 10.0122081 , 24.16407517,
       69.26691762, 62.57035615, 40.70024415, 88.09015081, 91.78351223,
       80.05458292, 85.84499489, 74.95211589, 66.60078613, 76.67009383,
       84.35904476,  5.60686584, 15.73205476,  8.41014595, 93.47481471,
       44.80653261, 24.51048993, 11.98116431, 51.75562447, 33.1942121 ,
        1.94286019, 13.64863858, 42.31348257, 22.71197698, 93.46380248,
       17.33270695, 85.00155317, 68.78571675,  9.36615752, 66.80058366,
       99.66088064, 73.47584896,  4.79834499, 73.90121724, 76.02816688,
       35.83169934, 10.45977551, 52.19877971, 40.98131335, 97.8276628 ,
       10.267353  , 41.21022813, 96.0116922 ,  2.84116844,  4.37028187,
       74.42741399, 44.16389499, 81.16473915, 20.0126378 , 83.90644473,
       57.28757503, 53.35324359, 61.82298049, 87.5587234 ,  5.98377328,
       84.3790549 , 70.11353301, 60.75059442,  5.1812638 , 77.15477412,
        3.18561882, 66.30296213, 39.58427537, 24.27703517, 13.32089264,
       17.28403112, 38.24671625, 97.87470914, 33.18708868,  9.39960223,
       26.25943921, 92.4985723 , 70.48717659, 34.84961875, 30.0418793 ,
       49.48830279, 82.39829221, 93.50267999, 62.29597315, 28.91784447,
       31.08075656,  8.38149478, 11.71095176,  6.67285889, 45.63449845,
       92.86176313, 63.6235834 , 14.69317318, 59.4582103 , 88.50597132,
       34.32488282, 19.23522563,  2.00631267, 31.42297503, 36.8667175 ,
       75.17909956, 61.98420462, 48.52704151, 29.77458278, 85.72620217,
       43.48340266, 71.94344121, 42.70595436, 76.72502626, 25.8622042 ,
       22.69986724,  3.68855157, 67.7849544 , 24.7906685 , 26.94807299,
       32.18556813, 64.08526658, 42.39734083, 29.95611559, 63.26719917,
       16.77199805, 38.83463718, 60.8589414 , 10.50848164, 62.98856979,
       54.16282638, 99.50014524, 75.84966616, 69.14368099, 50.50463563,
       37.38791866, 26.0741528 , 17.86249919, 36.66734475, 28.563868  ,
       45.89147815,  1.99863686, 81.1351946 , 12.5245012 , 77.68901133,
       86.23943648, 31.64155856, 43.14424013, 40.27907861, 21.76771364,
       73.85345375, 33.41771808, 15.6309728 , 49.02321873, 52.45109821,
       85.04344583, 93.95262213, 10.76827402, 45.66303944, 57.49365038,
       21.26615867, 81.76428821, 35.97538444, 60.00011792, 82.71683889,
       94.30219157, 45.30048765, 74.89825551, 91.81773008, 39.71788779,
       49.62308846, 62.40529259, 43.5847251 ,  7.68466623, 69.35093753,
       66.10250415, 86.2956585 , 43.20884042, 86.49504341, 83.46994007,
       85.95974719, 43.88450605, 10.69809671, 59.80599342, 35.96330641,
       88.60804359, 33.87965574, 29.49781551, 90.41536966, 42.16451465,
       82.76281801, 94.08354019, 53.94749417, 65.94218421, 84.8202422 ,
       95.32164812, 77.41927376, 69.41832977, 89.55197686,  5.24501226,
        7.61281197, 60.67062927, 23.2379831 , 35.42653858, 76.95177955,
       12.40553871, 44.16287556, 76.17526601, 74.68805637, 82.02275214,
       32.58105586, 79.89388516, 16.38037378, 33.02660963, 81.25583577,
       77.89614925, 78.16639362, 62.49087791, 85.49801288, 97.97921222,
       12.65455578, 76.83975061,  1.6016757 , 22.31685829, 95.37843552,
        5.73797398, 96.32945242, 36.16573819, 42.54915613, 22.46419891,
       81.29690703, 69.49837976, 71.82799429, 72.64941547, 71.96178624,
       49.44327586, 43.88167686, 33.86522577, 72.21646797, 70.08297348,
       19.07093327, 68.49027968, 46.42154002, 52.28316523, 38.19168046,
       35.31077934, 86.43289864, 92.46735407, 32.12992974, 76.74758793,
       58.45681834, 19.60979448, 90.85797064, 15.64578789, 59.38940813,
       47.27241147, 76.45140001, 36.21655494, 32.68772657, 29.04695174,
       51.43899409, 77.78200632, 43.51917173, 91.89714346, 25.6340627 ,
       47.13803297, 65.89708501, 12.76235734, 66.50333166, 34.36442577,
       12.93304699, 87.27067218, 83.52376566,  3.22209459, 72.11039829,
       93.0629285 , 31.70353215, 95.31203682, 41.57514648, 44.79920699,
       26.11732014, 22.87334888, 40.42866098, 53.73373315, 45.79896977,
       60.55135689, 89.44280737, 52.69497115, 90.67352998, 52.56018539,
       36.1374429 , 24.54824718, 31.0441528 , 36.69364818, 32.98404959,
       55.94966986, 15.19926124, 28.64662791, 66.79431981,  1.07505604,
       13.98902528, 34.07205555, 66.59099455, 53.99346341, 50.04168003,
       92.27901536, 89.07916361, 89.11364962, 35.30088029, 22.13131026,
       15.72976603, 26.31720959, 15.8030842 , 38.15643858, 43.05343958,
       20.8102516 , 58.91013795, 50.23771379, 34.23848456, 10.28818528,
       97.9482188 ,  4.23704112, 67.32591504, 49.56129789, 94.53246397,
       14.30798528, 94.82584534, 19.04027109, 94.61442562, 73.31695472,
       81.61653211, 26.8971173 , 28.62109901, 17.99097342, 71.3684911 ,
       76.67628128, 67.95915543, 75.08501068, 28.19786844, 68.85722217,
       69.55093709, 72.50202907, 29.95512677, 54.54439388, 26.27751693,
       82.69863116, 29.8383531 , 81.29818647, 12.88169333, 69.17915872,
       61.75740216, 64.68752497, 85.36152761, 92.84009582, 42.45454057,
       23.37647324, 97.32493874, 18.15238577, 49.18422127,  1.43274535,
       92.65234273, 73.12981462, 53.75895725, 50.14832693, 32.76258327,
       82.08319573, 95.90530813, 42.38811647, 53.5388985 , 42.90231447,
       14.34438958, 17.18257882, 90.67878163, 89.32725899,  7.01137818,
       93.67598611, 14.41231308, 12.56961658, 54.60090885, 11.14377515,
       29.85618125, 95.88135941, 97.18945139, 36.31713385, 10.0201595 ,
       46.62043796, 43.45926725, 90.09437169, 20.19135761, 85.59628195,
        4.12617838, 94.47207874, 50.22687205, 15.26985117, 25.57807086,
       36.69109128, 27.23945226, 42.31322278, 42.78440686, 76.47856059,
       28.94503989, 82.87157553, 95.53453178, 28.72048597, 39.31804539,
       18.17494053, 53.58260397, 51.73518316, 49.97894762, 12.60146182,
       99.01744444, 50.47782056, 78.85815911, 18.286918  , 46.01315435,
       91.71169522, 22.63698284, 17.00769651, 89.53167563, 39.85960576,
       50.24828166, 20.1894901 , 40.52630047, 95.95038833, 43.92741303,
       63.8010434 , 41.98080188, 35.73907738, 16.902058  , 94.91450021,
       77.17711297, 37.62276113, 18.74314226, 11.40639154,  4.56308659,
       73.63927335, 53.4758713 , 76.38001266, 30.05313151, 95.25325511,
       46.107474  , 55.31190272,  5.20462787, 72.17496449, 20.21585263,
       34.62785949, 31.86844808,  6.57335242, 42.21716401, 79.44993246,
        9.11662484, 80.51545433,  1.0382158 , 78.86443031, 16.27336516,
       42.14970583, 21.10719365, 89.52698031, 41.35764625, 33.57824416,
       47.67602957, 25.1917997 , 20.12458325, 15.64614671, 85.03157694,
       23.48679063, 54.28908938, 38.46060669, 34.36850785, 10.89430175,
       64.58201679, 78.73988379, 74.19839976, 50.32295222, 51.30740488,
       85.85169458, 81.8470305 , 93.66258193, 71.23098657,  8.22687402,
       39.85127361, 48.97046652, 65.70929396, 51.92591061, 69.67305211,
       94.17797327, 52.93146592, 65.99962763, 78.86430736, 77.43183817,
       74.94756027, 83.61491831, 12.15893432, 12.07075113, 45.46675984,
       95.04839838, 32.20233616, 44.46688141, 91.53960346, 19.33239893,
        9.99362375, 34.6157355 , 26.31975695, 21.54831203,  4.88235226,
       47.00863393, 31.84395168, 36.94065725, 97.75686832, 28.92606726,
       53.34390559, 83.76846255, 18.48153911, 27.86267163, 22.54577591,
       12.9689687 , 91.79847866, 75.72062935, 85.00024758, 89.45266002,
       77.36327174, 96.86618043, 69.82095269, 86.75679965,  9.9105089 ,
       65.29055557, 10.19458151, 77.60018073, 25.99859798, 41.94726883,
       14.15859768, 59.66802709, 73.61912463, 31.47907427, 35.74126946,
       14.79572787, 44.39774269, 33.88633908, 27.9771366 , 24.74792509,
       72.237029  , 53.02011534,  3.22917756, 36.10552896, 53.61955625,
       79.13168304, 67.918851  , 81.7256735 , 98.3217694 , 85.53170084,
       55.73138161, 65.87520504, 58.86346685, 52.73157662, 20.31070215,
       32.4519547 , 12.86217762, 82.10348782, 56.03250638, 29.63019956,
       62.27071095, 42.91057352, 74.642421  ,  9.33025924, 66.35273724,
       66.62594916, 58.46931003, 91.02169087, 20.68409622, 56.0921188 ,
        1.36746591, 20.42451057, 94.26056586, 67.43080512, 78.17988334,
       88.25145246, 83.10173559, 33.93329172, 30.09121231, 40.18733128,
       56.87811417, 31.75003848, 10.41447056, 42.24080004, 12.31832209,
        6.04443137, 34.33636886, 71.1930115 , 98.20386006, 37.77910654,
       95.14196636,  2.26945744, 52.76324207, 12.15967757, 38.56963429,
       42.96651662,  2.72458291,  8.74574043, 59.28565851, 89.95982511,
       54.32560446, 73.85455613, 60.15579522, 16.79993677, 63.01165857,
       90.05735205,  6.13511035, 83.85368913, 85.68575307, 61.53596284,
       50.52312526,  2.40870891, 34.0950038 , 34.86309733, 80.65563189,
       22.63208513, 33.53662906, 44.42780408, 31.29476854, 12.36484642,
       12.38425507,  6.79777596, 11.351853  , 27.119144  , 41.04171274,
       38.71594556,  7.5436278 ,  5.43481417, 38.61424029, 69.06191959,
       10.74451112, 36.62909769, 29.50791741, 50.01394021, 91.30597257,
       36.16977378, 46.24546915, 89.44677031, 32.43363685, 54.82896696,
       75.21114394, 52.37269231,  5.38441256, 16.10646315, 28.59478022,
       50.83643693,  7.3609162 , 25.47362095, 15.08094957, 11.27227154,
       25.4423912 , 41.85709128, 14.78523734, 41.291924  , 93.34565732])