In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Math Operations

### Operations on columns

In [6]:
# select a column and calculate total sum. without in() we will get np.int64(66089)
int(df_exams['math score'].sum())

66089

In [22]:
# count, mean, std, max, and min !!! without print did not work. without print only shows the last operation
print(df_exams['math score'].count())
print(df_exams['math score'].mean())
print(df_exams['math score'].std())
print(df_exams['math score'].max())
print(df_exams['math score'].min())

1000
66.089
15.16308009600945
100
0

In [16]:
# easier calculation with .describe()
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      69.169000
std      15.16308      14.600192      14.600192
min       0.00000      17.000000      17.000000
25%      57.00000      59.000000      59.000000
50%      66.00000      70.000000      70.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Operations on rows

In [17]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      216
1      249
2      280
3      161
4      232
      ...
995    286
996    172
997    201
998    224
999    249
Length: 1000, dtype: int64

In [19]:
# calculating the average score and assigning the result to a new column
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [20]:
# showing the dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,72,72.000000
1,female,group C,some college,standard,completed,69,90,90,83.000000
2,female,group B,master's degree,standard,none,90,95,95,93.333333
3,male,group A,associate's degree,free/reduced,none,47,57,57,53.666667
4,male,group C,some college,standard,none,76,78,78,77.333333
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,99,95.333333
996,male,group C,high school,free/reduced,none,62,55,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,71,67.000000
998,female,group D,some college,standard,completed,68,78,78,74.666667
999,female,group D,some college,free/reduced,none,77,86,86,83.000000